### ISSUE TITLE
Blank config page after install

### ISSUE THREAD

**Issue by xdespujols** [anfabio/upstart#6]
I have install on Firefox and Edge.

I have a blank page for properties and for 

![image](https://user-images.githubusercontent.com/17651187/143584365-deba37eb-d8b4-4713-a52d-aa3d93bc8f8f.png)

What is missing ?

**Comment by anfabio** [comment]
Hey xdespujols!

Try to access the main page first:
chrome-extension://ddalpldcidoajbgohbdlelfmfmjiccga/main.html

This will create the initial json config files.

**Comment by xdespujols** [comment]
Works fine

Thanks.
